### ISSUE TITLE
still having OMIM gene-disease mixups

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/dipper#273] opened 2016-02-25 23:58 UTC
http://www.omim.org/entry/208100
"http://purl.obolibrary.org/obo/OMIM_208100"  | ["AMCN","Neurogenic arthrogryposis multiplex congenita"] 

Is actually not correctly assigned as a gene in OMIM:
http://www.omim.org/entry/208100

it has a %, meaning:
A percent sign (%) before an entry number indicates that the entry describes a confirmed mendelian phenotype or phenotypic locus for which the underlying molecular basis is not known.

will report this one to them individually, but have we sent them these issues in bulk somehow? @nlwashington @kshefchek @jnguyenx @jmcmurry

**Comment by mellybelly** [comment] 2016-02-26 00:01
Clique in SciGraph

| "http://www.orpha.net/ORDO/Orphanet_1143" 	| "Neurogenic arthrogryposis multiplex congenita"      	|
| "http://purl.obolibrary.org/obo/MESH_C536614" | <null>                                               	|
| "http://identifiers.org/hgnc/HGNC:456"    	| "AMCN"                                               	|
| "http://purl.obolibrary.org/obo/OMIM_208100"  | ["AMCN","Neurogenic arthrogryposis multiplex congenita"] |

has two diseases and two genes

**Comment by kshefchek** [comment] 2016-02-26 00:56
I believe this comes from mondo and ncbigene.ttl

In MONDO:
NCBIGene:261 is a subClass of DOID:0050646, DOID:630

In ncbigene.ttl
NCBIGene:261 is typed as a SO:0000110
NCBIGene:261 sameAs OMIM:208100, HGNC:456

**Comment by mellybelly** [comment] 2016-02-26 01:05
OMIM says:
208100 is a phenotype entry and has an %.  Linkage studies have been
performed that give it a locus on the gene map.  On the gene map it
has a phenotype mapping key of 2.  All of this is correct for how we
handle genes and phenotypes.  AMCN is not a gene.   It's placement
on the map statistical (linkage) and does not related directly, as
yet, to sequence.  Should a mutation in a gene be found, 208100 would get a #, the phenotype would move to the gene with a phenotype mapping key of 3.

**Comment by mellybelly** [comment] 2016-02-26 01:06
I wish these were loci and not phenotypes!

**Comment by kshefchek** [comment] 2016-02-26 01:32
Mondo and OMIM categorize the omim id as a disease.  Theoretically, in our world the omim id can be the disease and the ncbigene a heritable phenotypic marker.  We would just need to remove the equivalency in ncbigene.ttl, potentially by checking mondo for type inconsistencies.

**Comment by kshefchek** [comment] 2016-05-23 14:21
I've mocked up a solution in my current PR, see https://github.com/kshefchek/dipper/commit/dda6240fb17beef2dc010f36e15e4973097ed4b8

When processing NCBIGene-OMIM equivalencies, we check scigraph to see if the OMIM ID is a disease.  This will allow us to model the NCBIGene as the phenotypic marker, and the OMIM ID as a gene (determined by MONDO).  cc @mellybelly @cmungall

**Comment by cmungall** [comment] 2016-05-23 17:12
circularity - MonDO gets this from the ttl exported by dipper; 
specifically if it's a subclass of SO:0000704

e.g.

```
OBO:OMIM_103890 a owl:Class ;
     rdfs:label "ARM" ;
     dc:description "Aldose Reductase M" ;
     OIO:hasDbXref OBO:UMLS_C1863110 ;
     OIO:hasExactSynonym "ALDOSE REDUCTASE M; ARM",
         "ARM" ;
     rdfs:subClassOf OBO:SO_0000704 .
```

**Comment by kshefchek** [comment] 2016-05-23 17:54
This is an update to the NCBIGene parser, not OMIM.  The above is from OMIM.ttl correct?

**Comment by TomConlin** [comment] 2016-05-27 17:22
I left a note in the OMIM.py file after switching to the mim2gene.txt file.

# TODO: having the omim IDs typed like this should be used later.

there may be information available which we are not taking advantage of 
to type the OMIM identifiers.

**Comment by kshefchek** [comment] 2016-05-27 18:52
I think the issue is that OMIM conflates loci and phenotypes, and @nlwashington's approach was to treat the equivalent NCBIGene as the loci and the OMIM id as the phenotype.  If this is the right approach then it should be fixed in the next scigraph load by bringing in the new ncbi gene file.

**Comment by kshefchek** [comment] 2016-10-10 21:54
This should be fixed as of our September data release, see https://github.com/monarch-initiative/dipper/pull/357, unit tests added to the monarch-app.

**Comment by kshefchek** [comment] 2017-03-08 00:15
These are back,

**Closed** 2018-03-23 16:59 UTC
Labels: equivalence-bug, identifiers, omim
