### ISSUE TITLE
Gene and species

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/dipper#176] opened 2015-08-03 06:06 UTC
Not sure if we had this before, but this page is not showing the species
http://beta.monarchinitiative.org/gene/NCBIGene:100518132

Gene: LOC100518132
Organism: Not Specified

it should be straightforward to get species info from the Entrez Gene files.

**Comment by nlwashington** [comment] 2015-08-03 07:00
The taxon data is already loaded the graph:
http://duckworth.crbs.ucsd.edu:9000/scigraph/graph/neighbors/NCBIGene:100518132?depth=1&blankNodes=true&relationshipType=RO_0002162&direction=BOTH&project=%2A

@kshefchek please check on why it's not showing up in the interface.

**Comment by kshefchek** [comment] 2015-08-03 18:25
Duplicate of https://github.com/monarch-initiative/monarch-app/issues/876

**Closed by kshefchek** 2015-08-03 18:25 UTC
